name = "feedback-tracker-api"
main = "src/index.ts"
compatibility_date = "2026-02-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "feedback-tracker-db"
database_id = "c755698f-7332-4198-b4bd-b29b21aef9b0"

[[kv_namespaces]]
binding = "CACHE"
id = "66823948eeac44a48621707ec8ed0b77"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "feedback-attachments"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "feedback_search"
